version: '3.8'

services:
  cliente-app:
    build:
      context: ./cliente
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cliente-db:5432/clientesdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - cliente-db 

  cliente-db:
    image: postgres:15
    container_name: postgres-clientes
    environment:
      POSTGRES_DB: clientesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432" 
    volumes:
      - clientes_db_data:/var/lib/postgresql/data 

  veiculo-app:
    build:
      context: ./veiculo
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://veiculo-db:5432/veiculosdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - veiculo-db

  veiculo-db:
    image: postgres:15
    container_name: postgres-veiculos
    environment:
      POSTGRES_DB: veiculosdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - veiculo_db_data:/var/lib/postgresql/data

  funcionario-app:
    build:
      context: ./funcionario
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://funcionario-db:5432/funcionariosdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - funcionario-db

  funcionario-db:
    image: postgres:15
    container_name: postgres-funcionarios
    environment:
      POSTGRES_DB: funcionariosdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5435:5432"
    volumes:
      - funcionarios_db_data:/var/lib/postgresql/data

  ordem-servico-app:
    build:
      context: ./ordemServico
      dockerfile: Dockerfile
    ports:
      - "6060:6060"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ordem-servico-db:5432/ordemServicosdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - ordem-servico-db

  ordem-servico-db:
    image: postgres:15
    container_name: postgres-ordemServicos
    environment:
      POSTGRES_DB: ordemServicosdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5436:5432"
    volumes:
      - ordem_servicos_db_data:/var/lib/postgresql/data

volumes:
  clientes_db_data: 
  veiculo_db_data: 
  funcionarios_db_data:
  ordem_servicos_db_data:
